# Generated by Django 3.0.8 on 2020-08-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('char1', models.TextField(blank=True, null=True)),
                ('char2', models.TextField(blank=True, null=True)),
                ('char3', models.TextField(blank=True, null=True)),
                ('char4', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
