# Generated by Django 3.0.8 on 2020-08-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='items1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bb',
            name='items2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bb',
            name='items3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bb',
            name='items4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bb',
            name='char1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bb',
            name='char2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bb',
            name='char3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bb',
            name='char4',
            field=models.CharField(max_length=50),
        ),
    ]
