# Generated by Django 3.0.8 on 2020-08-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_auto_20200803_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['published'], 'verbose_name': 'Билд', 'verbose_name_plural': 'Билды'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='char1',
            field=models.CharField(max_length=50, verbose_name='Профа первого чара'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='char2',
            field=models.CharField(max_length=50, verbose_name='Профа второго чара'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='char3',
            field=models.CharField(max_length=50, verbose_name='Профа третьего чара'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='char4',
            field=models.CharField(max_length=50, verbose_name='Профа четвертого чара'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='items1',
            field=models.TextField(blank=True, null=True, verbose_name='Шмот первого чара'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='items2',
            field=models.TextField(blank=True, null=True, verbose_name='Шмот второго чара'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='items3',
            field=models.TextField(blank=True, null=True, verbose_name='Шмот третьего чара'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='items4',
            field=models.TextField(blank=True, null=True, verbose_name='Шмот четвертого чара'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Билд'),
        ),
        migrations.AddField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='builds.Rubric', verbose_name='Рубрика'),
        ),
    ]
